# Generated by Django 6.0.7 on 2026-07-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_most_played',
            field=models.BooleanField(default=False),
        ),
    ]
